title: DeLaVeaga Disc Golf
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Top of the world
color:
  saturation: 0.4796587
  brandStrength: 0.5279003351461142
  lightness: 0.1821719
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  rhythmicContrast: 0.2921147
navigation:
  - name: ' About us'
    id: a9684dc5-b338-4e4e-a924-7f0812c28f99
    type: content
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: De LaVeaga Disc Golf
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2562724
layout_spectrum: 0.2336673911195248
