title: DeLaVeaga Disc Golf
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Top of the world
color:
  saturation: 0.5232975
  brandStrength: 0.5279003351461142
  lightness: 0.4731183
  brandColors:
    - '#496B53'
    - '#4F787A'
    - '#79AFD5'
    - '#6799B0'
    - '#35484F'
  rhythmicContrast: 0.6146954
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: De LaVeaga Disc Golf
favicon: null
navigation:
  - name: ' About us'
    id: a9684dc5-b338-4e4e-a924-7f0812c28f99
    type: content
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6899642
layout_spectrum: 0
