name: De LaVeaga Disc Golf
favicon: null
layout_spectrum: 0.4985856718849391
typography_spectrum: 0.6118700772058219
navigation:
  - name: PDGA
    url: 'http://www.pdga.com'
    type: external
  - name: Pinto Lake DG Course
    url: 'http://www.pintolakediscgolf.com'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: DeLaVeaga Disc Golf
description: ''
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#31455E'
    - '#AFC1D9'
    - '#DDE3EF'
    - '#848952'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
