typography_spectrum: 0.9820586701389402
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.5279003351461142
  lightness: 0.18217188818380237
  saturation: 0.4796587284654379
  rhythmicContrast: 0.045425045769661665
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23366739111952484
analytics:
  google: null
  facebook: null
  twitter: null
name: De LaVeaga Disc Golf
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ' Events'
    id: a9684dc5-b338-4e4e-a924-7f0812c28f99
    type: content
  - name: 'Events:'
    id: a79a8371-cab3-425c-99eb-eecdfeeb2ae7
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: DeLaVeaga Disc Golf
description: Top of the world
purpose: []
