layout_spectrum: 0.303075167350471
typography_spectrum: 0.49896586313843727
color:
  saturation: 0.4547512272838503
  brandStrength: 0.37548833014443517
  lightness: 0.19098799745552242
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  rhythmicContrast: 0.058584903832525015
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
name: De LaVeaga Disc Golf
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: PDGA
    url: 'http://www.pdga.com'
    type: external
  - name: Pinto Lake DG Course
    url: 'http://www.pintolakediscgolf.com'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: DeLaVeaga Disc Golf
description: ''
purpose: []
